//This is the data that will probably come from the server

const data = {
  'web-development': {
    title: 'Web Development',
    imageSource: '/images/web-development.jpg',
    tileItems: [
      {
        id: 'vbet',
        alt: 'VBet',
        imageSource: '/images/web-development/vbet.jpg',
        link: '/home/web-development/vbet',
        title: 'VBet',
      },
      {
        id: 'agency-agile',
        alt: 'Agency Agile',
        imageSource: '/images/web-development/agency-agile.jpg',
        link: '/home/web-development/agency-agile',
        title: 'Agency Agile',
      },
      {
        id: 'phoenix-energy',
        alt: 'Phoenix Energy',
        imageSource: '/images/web-development/phoenix-energy.jpg',
        link: '/home/web-development/phoenix-energy',
        title: 'Phoenix Energy',
      },
      {
        id: 'davydova-london',
        alt: 'Davydova London',
        imageSource: '/images/web-development/davydova-london.jpg',
        link: '/home/web-development/davydova-london',
        title: 'Davydova London',
      },
      {
        id: 'auto-eagle',
        alt: 'Auto Eagle',
        imageSource: '/images/web-development/auto-eagle.jpg',
        link: '/home/web-development/auto-eagle',
        title: 'Auto Eagle',
      },
      {
        id: 'unarm',
        alt: 'Unarm',
        imageSource: '/images/web-development/unarm.jpg',
        link: '/home/web-development/unarm',
        title: 'Unarm',
      },
      {
        id: 'food-rusi',
        alt: 'Food Rusi',
        imageSource: '/images/web-development/food-rusi.jpg',
        link: '/home/web-development/food-rusi',
        title: 'Food Rusi',
      },
      {
        id: 'colibri-bookstore',
        alt: 'Colibri Bookstore',
        imageSource: '/images/web-development/colibri-bookstore.jpg',
        link: '/home/web-development/colibri-bookstore',
        title: 'Colibri Bookstore',
      },
      {
        id: 'fightclub-slava',
        alt: 'Fight Club Slava',
        imageSource: '/images/web-development/fightclub-slava.jpg',
        link: '/home/web-development/fightclub-slava',
        title: 'Fight Club Slava',
      },
      {
        id: 'optics',
        alt: 'Optics',
        imageSource: '/images/web-development/optics.jpg',
        link: '/home/web-development/optics',
        title: 'Optics',
      },
      {
        id: 'best-cart',
        alt: 'Best Cart',
        imageSource: '/images/web-development/best-cart.jpg',
        link: '/home/web-development/best-cart',
        title: 'Best Cart',
      },
    ],
  },
  'mobile-apps': {
    title: 'Mobile Apps',
    imageSource: '/images/mobile-apps.jpg',
    tileItems: [
      {
        id: 'nude',
        alt: 'Nude',
        imageSource: '/images/mobile-apps/nude.jpg',
        link: '/home/mobile-apps/nude',
        title: 'Nude',
      },
    ],
  },
  'desktop-apps': {
    title: 'Desktop & Web Apps',
    imageSource: '/images/desktop-apps.jpg',
    tileItems: [],
  },
  'digital-marketing': {
    title: 'Digital Marketing',
    imageSource: '/images/digital-marketing.jpg',
    tileItems: [
      {
        id: 'best-cart',
        alt: 'Best Cart',
        imageSource: '/images/digital-marketing/best-cart.jpg',
        link: '/home/digital-marketing/best-cart',
        title: 'Best Cart',
      },
      {
        id: 'food-rusi',
        alt: 'Food Rusi',
        imageSource: '/images/digital-marketing/food-rusi.jpg',
        link: '/home/digital-marketing/food-rusi',
        title: 'Food Rusi',
      },
    ],
  },
  'graphic-design': {
    title: 'Graphic Design',
    imageSource: '/images/graphic-design.jpg',
    tileItems: [
      {
        id: 'auto-eagle',
        alt: 'Auto Eagle',
        imageSource: '/images/graphic-design/auto-eagle.jpg',
        link: '/home/graphic-design/auto-eagle',
        title: 'Auto Eagle',
      },
      {
        id: 'unarm',
        alt: 'Unarm',
        imageSource: '/images/graphic-design/unarm.jpg',
        link: '/home/graphic-design/unarm',
        title: 'Unarm',
      },
      {
        id: 'yerewok',
        alt: 'Yerewok',
        imageSource: '/images/graphic-design/yerewok.jpg',
        link: '/home/graphic-design/yerewok',
        title: 'Yerewok',
      },
      {
        id: 'mata-toys',
        alt: 'Mata Toys',
        imageSource: '/images/graphic-design/mata-toys.jpg',
        link: '/home/graphic-design/mata-toys',
        title: 'Mata Toys',
      },
      {
        id: 'best-cart',
        alt: 'Best Cart',
        imageSource: '/images/graphic-design/best-cart.jpg',
        link: '/home/graphic-design/best-cart',
        title: 'Best Cart',
      },
      {
        id: 'optics',
        alt: 'Optics.am',
        imageSource: '/images/graphic-design/optics.jpg',
        link: '/home/graphic-design/optics',
        title: 'Optics.am',
      },
      {
        id: 'biocotton',
        alt: 'Biocotton',
        imageSource: '/images/graphic-design/biocotton.jpg',
        link: '/home/graphic-design/biocotton',
        title: 'Biocotton',
      },
      {
        id: 'wild-musicians',
        alt: 'Wild Musicians',
        imageSource: '/images/graphic-design/wild-musicians.jpg',
        link: '/home/graphic-design/wild-musicians',
        title: 'Wild Musicians',
      },
      {
        id: 'opera',
        alt: 'Opera',
        imageSource: '/images/graphic-design/opera.jpg',
        link: '/home/graphic-design/opera',
        title: 'Opera',
      },
      {
        id: 'republic-square',
        alt: 'Republic Square',
        imageSource: '/images/graphic-design/republic-square.jpg',
        link: '/home/graphic-design/republic-square',
        title: 'Republic Square',
      },
      {
        id: 'khor-virap',
        alt: 'Khor Virap',
        imageSource: '/images/graphic-design/khor-virap.jpg',
        link: '/home/graphic-design/khor-virap',
        title: 'Khor Virap',
      },
    ],
  },
  'animation': {
    title: 'Animation',
    imageSource: '/images/animation.jpg',
    tileItems: [
      {
        id: '',
        alt: '',
        imageSource: '/images/',
        link: '',
        title: '',
      },
    ],
  },
};

export default data;
